import { describe, it, expect } from "vitest";
import type { Skill }           from "@evolver/core";
import { SkillConverter }       from "../src/skill-converter.js";

describe("SkillConverter", () => {
  it("SKILL.md를 AGENTS.md 섹션으로 변환", () => {
    const skill: Skill = {
      name:    "data-extraction",
      trigger: "extracting data from tables",
      content: "Extract structured data from HTML tables",
    };
    const section = SkillConverter.toAgentsMd(skill);

    expect(section).toContain("## data-extraction");
    expect(section).toContain("**Trigger:** extracting data from tables");
    expect(section).toContain("Extract structured data from HTML tables");
  });

  it("여러 스킬을 AGENTS.md로 병합", () => {
    const skills: Skill[] = [
      { name: "a", trigger: "t1", content: "c1" },
      { name: "b", trigger: "t2", content: "c2" },
    ];
    const merged = SkillConverter.mergeAgentsMd(skills);

    expect(merged).toContain("# AGENTS.md");
    expect(merged).toContain("## a");
    expect(merged).toContain("## b");
    expect(merged).toContain("**Trigger:** t1");
    expect(merged).toContain("**Trigger:** t2");
    expect(merged).toContain("c1");
    expect(merged).toContain("c2");
  });

  it("빈 스킬 배열에서도 헤더를 포함한 문서를 반환", () => {
    const merged = SkillConverter.mergeAgentsMd([]);

    expect(merged).toContain("# AGENTS.md");
    expect(merged).toContain("Auto-generated by Evolver");
  });

  it("스킬 content에 마크다운이 포함되어도 그대로 보존", () => {
    const skill: Skill = {
      name:    "complex",
      trigger: "complex tasks",
      content: "# Heading\n\n- item 1\n- item 2\n\n```js\nconsole.log('hello');\n```",
    };
    const section = SkillConverter.toAgentsMd(skill);

    expect(section).toContain("# Heading");
    expect(section).toContain("```js");
    expect(section).toContain("console.log('hello');");
  });
});
