/**
 * SKILL.md 형식을 Codex의 AGENTS.md 형식으로 변환한다.
 *
 * 각 Skill은 AGENTS.md 내 하나의 섹션(## heading)으로 매핑되며,
 * 여러 스킬을 하나의 AGENTS.md 파일로 병합할 수 있다.
 */

import type { Skill } from "@nerdvana/evolver-core";

export class SkillConverter {
  /**
   * 단일 Skill을 AGENTS.md 섹션 문자열로 변환한다.
   */
  static toAgentsMd(skill: Skill): string {
    const lines: string[] = [
      `## ${skill.name}`,
      "",
      `**Trigger:** ${skill.trigger}`,
      "",
      skill.content,
    ];
    return lines.join("\n");
  }

  /**
   * 여러 Skill을 하나의 AGENTS.md 문서로 병합한다.
   */
  static mergeAgentsMd(skills: Skill[]): string {
    const header = "# AGENTS.md\n\n> Auto-generated by Evolver.\n";
    const sections = skills.map((s) => SkillConverter.toAgentsMd(s));
    return [header, ...sections].join("\n\n");
  }
}
